### ISSUE TITLE
Compile fails with Boost 1.70 or 1.71

### ISSUE THREAD

**Issue by rhastie** [sony/nmos-cpp#102] opened 2019-11-27 13:36 UTC
Have you used Boost 1.70 or 1.71 yet?

I was trying to advance the dependencies and there appears to be something that the code is using that’s now been deprecated.

The highest I can get to with a successful compile is Boost 1.69. Just interested to know if you are aware?

It's not blocking anything currently... Thanks

**Comment by garethsb-sony** [comment] 2019-11-27 15:57
Root cause is an API change in Boost.Asio, which affects websocketpp (and a gazillion other people). There has been a patch for websocketpp for six months (https://github.com/zaphoyd/websocketpp/pull/814) but although it's been merged to 'develop' branch it hasn't made it into 'master' or a release unfortunately.

**Comment by garethsb-sony** [comment] 2020-03-19 18:21
I have tried moving to websocketpp develop branch (currently https://github.com/zaphoyd/websocketpp/commit/bc0dc579a58424d6874f04f7e7b03eaae1f35d0f), with Boost 1.72.0, and have successfully compiled and tested nmos-cpp on Windows (VC 2019) and Linux (gcc 9.2). (There are still a few warnings like those mentioned in #86, so I may investigate merging other patches to a fork of websocketpp develop also.)

**Comment by garethsb-sony** [comment] 2020-05-05 21:23
Resolved by websocketpp 0.8.2 which is specified with cpprestsdk 2.10.16 via the conanfile

**Closed by garethsb-sony** 2020-05-05 21:23 UTC
Labels: dependency issue
