### ISSUE TITLE
Cmake error for nmos-cpp under Ubuntu16.04(Virtualbox and Vagrant)

### ISSUE THREAD

**Issue by soutaroumaejima** [sony/nmos-cpp#21] opened 2018-08-10 08:04 UTC
I think I have completed set-up of all dependencies successfully(C++ REST SDK, Boost C++,  mdns etc). However,  the result of cmake of nmos-cpp was failure. That is error message.

> vagrant@vagrant:~/nmos-cpp/Development/build$ cmake -DCMAKE_BUILD_TYPE:STRING="Release" -DWERROR:BOOL="0" -DWEBSOCKETPP_INCLUDE_DIR=$HOME/cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp -DBOOST_INCLUDEDIR:PATH="$HOME/boost_1_67_0" -DBOOST_LIBRARYDIR:PATH="$HOME/boost_1_67_0/lib" -DCPPREST_INCLUDE_DIR:PATH="$HOME/cpprestsdk-2.10.2-nmos-cpp/" ..
> 
> CMake Error at /home/vagrant/cpprestsdk-2.10.2-nmos-cpp/Release/build/src/cpprestsdk-config.cmake:17 (include):
>   include could not find load file:
> 
>     /home/vagrant/cpprestsdk-2.10.2-nmos-cpp/Release/build/src/cpprestsdk-targets.cmake
> Call Stack (most recent call first):
>   CMakeLists.txt:33 (find_package)
> 
> -- Found cpprestsdk
> CMake Error at CMakeLists.txt:37 (get_target_property):
>   get_target_property() called with non-existent target
>   "cpprestsdk::cpprest".
> 
> -- Using configured websocketpp include directory at /home/vagrant/cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp
> -- Boost version: 1.67.0
> -- Found the following Boost libraries:
> --   system
> --   date_time
> --   regex
> --   thread
> --   chrono
> --   atomic
> -- Configuring incomplete, errors occurred!
> See also "/home/vagrant/nmos-cpp/Development/build/CMakeFiles/CMakeOutput.log".
> See also "/home/vagrant/nmos-cpp/Development/build/CMakeFiles/CMakeError.log".

I think that cause of the error is maybe not existing of [cpprestsdk-config.cmake] in [/home/vagrant/cpprestsdk-2.10.2-nmos-cpp/Release/build/src/].
But I can't conceive how to solve this error.

**Comment by garethsb-sony** [comment] 2018-08-10 09:58
Thanks for your question. Did you ``make`` and ``sudo make install`` C++ REST SDK itself before nmos-cpp?

**Comment by soutaroumaejima** [comment] 2018-08-10 10:18
Thank you for your quick response!
Sorry, perhaps I didn't ''make'' and ''make install''.
I will try that command.

I want to know if this command is correct for achievement of your comment.
--------------------------------------------------------------------
cd ~/cpprestsdk-2.10.2-nmos-cpp/Release
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE:STRING="Release" -DWERROR:BOOL="0" ..
make
sudo make install
--------------------------------------------------------------------------------

**Comment by garethsb-sony** [comment] 2018-08-10 10:48
Yes, please try that.

**Comment by garethsb-sony** [comment] 2018-08-16 11:16
@soutaroumaejima Have you now been able to build everything successfully?

**Comment by soutaroumaejima** [comment] 2018-08-20 01:25
`make` and `sudo make install `C++ REST SDK itself was a success.

**Comment by soutaroumaejima** [comment] 2018-08-20 06:52
Next, I will try Run Tests and report about it later. 
Please let me question if something also happen...

**Comment by garethsb-sony** [comment] 2018-08-21 11:35
You do not need to specify the ``-DWEBSOCKETPP_INCLUDE_DIR=`` option when running cmake for cpprestsdk, only when running cmake for nmos-cpp. As you can see from your message logs, the cpprestsdk CMakeLists ignores ``WEBSOCKETPP_INCLUDE_DIR``.

> I think the cause of it is difference of used websocketpp(pre-installed in OS or embedded version in cpprestsdk-2.10.2-nmos-cpp). Is my understanding correct?

I have not recently tried building nmos-cpp with different WebSocket++ than used by cpprestsdk, but it worked in the past. So I am not sure that this is the cause of your trouble.

Is your problem still that when running cmake for nmos-cpp, you see the error "Could not find a package configuration file for cpprestsdk"?

After cpprestsdk ``make install`` can you see the installed ``cpprestsdk-config.cmake`` file?

If os, have you tried using``CMAKE_PREFIX_PATH`` or specifying ``cpprestsdk_DIR`` as suggested in the cmake error message?

**Comment by soutaroumaejima** [comment] 2018-08-22 04:13
`You do not need to specify the -DWEBSOCKETPP_INCLUDE_DIR= option when running cmake for cpprestsdk, only when running cmake for nmos-cpp. As you can see from your message logs, the cpprestsdk CMakeLists ignores WEBSOCKETPP_INCLUDE_DIR.`

**Comment by soutaroumaejima** [comment] 2018-08-22 04:52
After such setup of cpprestsdk, nmos-cpp were build successfully and I ran nmos-cppregistry-test.
That is the message after test. Is this going well?

```
maejima@ubuntu:~/nmos-cpp/Development/build$ sudo cmake -DCMAKE_BUILD_TYPE:STRING="Release" -DWERROR:BOOL="0" -DWEBSOCKETPP_INCLUDE_DIR=$HOME/cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp -DBOOST_INCLUDEDIR:PATH="$HOME/boost_1_67_0" -DBOOST_LIBRARYDIR:PATH="$HOME/boost_1_67_0/lib" ..
-- Found cpprestsdk
-- Using configured websocketpp include directory at /home/maejima/cpprestsdk-2.10.2-nmos-cpp/Release/libs/websocketpp
-- Boost version: 1.67.0
-- Found the following Boost libraries:
--   system
--   date_time
--   regex
--   thread
--   chrono
--   atomic
-- Configuring done
-- Generating done
-- Build files have been written to: /home/maejima/nmos-cpp/Development/build
maejima@ubuntu:~/nmos-cpp/Development/build$ sudo make
[  3%] Built target mdns_static
[ 10%] Built target nmos-cpp-registry-test
[ 11%] Built target json_schema_validator_static
[ 74%] Built target nmos_is04_schemas_static
[ 89%] Built target nmos-cpp-registry
[100%] Built target nmos-cpp-node
maejima@ubuntu:~/nmos-cpp/Development/build$ ./nmos-cpp-registry-test
===============================================================================
All tests passed (260 assertions in 30 test cases)

```

**Comment by garethsb-sony** [comment] 2018-08-22 07:59
I'm very glad you have now successfully built nmos-cpp!

The "All tests passed" result of the test suite is good news (although the coverage is limited at the moment).

The next thing to try is to run ``nmos-cpp-registry`` and one or more ``nmos-cpp-node`` as in the [Tutorial](https://github.com/sony/nmos-cpp/blob/master/Documents/Tutorial.md). If you run them on the same host, remember to specify unique port numbers for the nodes, like so:

```
.\nmos-cpp-registry
.\nmos-cpp-node "{\"node_port\": 10001, \"connection_port\": 10002, \"settings_port\": 10003, \"logging_port\": 10004}"
```

(Depending on whether you have chosen Avahi or mdnsResponder for DNS-SD, ``avahi-daemon`` or ``mdnsd`` must be already started too.)

Since the build is successful, I will close this issue.

**Closed by garethsb-sony** 2018-08-22 07:59 UTC
