### ISSUE TITLE
Exclude libcmt only for dynamic runtime linkage

### ISSUE THREAD

**Issue by aholzinger** [sony/nmos-cpp#129] opened 2020-03-11 10:50 UTC
With this patch
https://github.com/aholzinger/nmos-cpp/commit/a99379ea48c085145affa9d67198353e116819c5
libcmt is only excluded for dynamic runtime builds on Windows.

Without this patch building release builds on Windows with static runtime linkage aren't possible.

**Comment by garethsb-sony** [comment] 2020-03-11 11:02
Let's investigate again why we had to explicitly remove **libcmt** at all.

**Comment by aholzinger** [comment] 2020-03-11 11:22
Sometimes by configuration issues a library is used for linking that was built with static runtime (/MT or /MTd) will be used also in a dynamic link (/MD or /MDd) in a dynamic build. Then as a work-around one can exclude libcmt (but for the debug build libcmtd would have to be excluded).

In a static release build (/MT) libcmt is needed, excluding it makes the build fail. As in a static debug build (/MTd) libcmtd is needed.

I can successfully build nmos-cpp with this changes for both staic builds, debug and release. Dynamic builds aren't affected so IMHO the path is fine.

**Comment by garethsb-sony** [comment] 2020-03-11 11:31
> Sometimes by configuration issues a library is used for linking that was built with static runtime (/MT or /MTd) will be used also in a dynamic link (/MD or /MDd) in a dynamic build. Then as a work-around one can exclude libcmt (but for the debug build libcmtd would have to be excluded).

Right, except that I seem to remember that the issue here was a dependency (perhaps OpenSSL) that only provided a release static build. As I said, a bit of investigation required to confirm.

**Comment by garethsb-sony** [comment] 2020-03-12 22:18
OK, the problem is the Bonjour SDK's shim **dnssd.lib** for which only a /MT build is provided. It took me a while to identify this, as we now only link that lib when the nmos-cpp CMake option `MDNS_SYSTEM_BONJOUR` is explicitly set `ON`, normally we build the shim from source in order to incorporate a patch.

So, although the `NODEFAULTLIB:libcmt` is now usually not required, I think I'll incorporate your proposed patch.

Thanks!

**Comment by garethsb-sony** [comment] 2020-03-13 10:07
I hope c097aa5911afce99a81e268a56fea7501a0c9002 will resolve this. Review appreciated!

**Comment by aholzinger** [comment] 2020-03-15 14:01
I think this a very good solution as it also supports CMake < 3.15.

It's my understanding that `CMAKE_MSVC_RUNTIME_LIBRARY` will not be set by the generator, but only by the user or in case not the default will be dynamic runtime linking (where in the release case libcmt has to be removed):
[https://cmake.org/cmake/help/v3.15/policy/CMP0091.html#policy:CMP0091](url)

I tested the following Windows Visual Studio 2019 builds with CMake 3.16 using `CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>` resp. `CMAKE_MSVC_RUNTIME_LIBRARY=MultiThreaded$<$<CONFIG:Debug>:Debug>DLL`:
x86 debug MTd
x86 release MT
x86 debug MDd
x86 release MD
x64 debug MTd
x64 release MT
x64 debug MDd
x64 release MD
All builds succeeded.

The only two builds for which the exclusion of libcmt is an issue are
x86 release MT
x64 release MT
because only those do need to link libcmt.lib.

These two builds only do work, when `CMAKE_MSVC_RUNTIME_LIBRARY` is used and set to **MultiThreaded**. If someone uses CMake >= 3.15 and the old `CMAKE_CXX_FLAGS` method to build a static runtime build under Windows, I think the two above builds will fail, but I think this is okay as for CMake >= 3.15 `CMAKE_MSVC_RUNTIME_LIBRARY` is the way to go.

**Comment by garethsb-sony** [comment] 2020-03-16 07:12
Great, I agree with your conclusion. Closing this one...

**Closed by garethsb-sony** 2020-03-16 07:12 UTC
